### ISSUE TITLE
[Topic Suggestion]

### ISSUE THREAD

**Issue by smartsubbi** [samanthaming/samanthaming.com#11]
### Category

- [ x ] Tidbit
- [ ] Article
- [ ] Video
- [ ] Podcast

_Don't forget to apply a Label if applicable_

**Comment by samanthaming** [comment]
@smartsubbi hmm...you didn't indicate the topic you would like me to look into 🤔 Maybe you were trying to create a test issue 😅 I'm going to close this as there is no detail provided. Please feel free to open another ticket with a **Topic Suggestion** if something come to mind 🙂👍
