### ISSUE TITLE
Broken Social Media LINKS on About Me page's aside element

### ISSUE THREAD

**Issue by garricode** [samanthaming/samanthaming.com#12]
When I clicked, in an Social Media link from the aside element,  it sends me to a 404 No Found Page. The Social Media links work in contact page; nav and footer elements work well too.

### Example ###

If the `<a>` element for Github contains this link, https://www.samanthaming.com/about/https:/github.com/samanthaming/, it leads to a 404 No Found page.

### Expected Behavior ###

I expected it to direct me the social pages as happened on the other elements (nav and footer).
### Screenshots

**Aside Element in About Me Page ❌**
![aside-element](https://user-images.githubusercontent.com/16749350/74705813-c2bb5a00-51da-11ea-9f1c-51b19d082ebb.png)

**404 No Found Page ❌**
![404](https://user-images.githubusercontent.com/16749350/74705821-c9e26800-51da-11ea-8887-7095d8bdff75.png)

**Contact Page ✔️**
![contact-page](https://user-images.githubusercontent.com/16749350/74705829-cf3fb280-51da-11ea-8854-c9085dc44a53.png)

### Fix Suggestion

Double check to understand why is this happening. I did not have success on my end by editing on Chrome DevTools.

`<a href="https://github.com/samanthaming/" class="flex items-center hover:text-fuscia hover-transition-fast hover:underline">
`

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Device Affected

- [X] Mobile
- [X] Tablet
- [X] Computer

**Comment by samanthaming** [comment]
@garricode thank you so much for letting me know of this bug 😱and provided so much information 👏  I'll look into it this weekend and get it fixed! 💪

**Comment by garricode** [comment]
@samanthaming I just checked them. 

✔️ The Social Media LINKS on About Me page's aside element are working.

I am closing the issue. Thank you for your time on looking into it 😊.
