### ISSUE TITLE
[Bug Report] Mobile Device Scroll Issue

### ISSUE THREAD

**Issue by JSsquare** [samanthaming/samanthaming.com#14]
### Describe the bug
Go down and start scrolling horizontally on Top TidBits. And then try to scroll vertically. It doesn't allow me to scroll vertically anymore.

### Steps to Reproduce
Go down and start scrolling horizontally on Top TidBits. And then try to scroll vertically

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Device Affected

- [x] Mobile (Pixel 3)
- [ ] Tablet
- [ ] Computer

**Comment by samanthaming** [comment]
@JSsquare thanks so much for letting me know this issue 😱 I think I have a fix in place! So I'm going to close this ticket. If it still persists, please just let me know. We can reopen this ticket 💪
