### ISSUE TITLE
Feature - PWA

### ISSUE THREAD

**Issue by sujeetjaiswara** [samanthaming/samanthaming.com#24]
Hi Samantha Ming,
It's a nice experience if you enabled your website with the progressive web app. (like https://alligator.io/)

Best regards - Sujeet Jaiswara

**Comment by samanthaming** [comment]
For sure! This is what I want to work on as well! There is an existing issue on this (which just means I really need to get on this 😅), so I'm going close this issue and just keep one in the pipeline. Thanks for this feature request! 😄 

https://github.com/samanthaming/samanthaming.com/issues/13
