### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by baker-d** [samanthaming/samanthaming.com#4]
### Describe the bug

404 - Page not found

### Steps to Reproduce
1. Go to 'My Top 3 Favorite FREE JavaScript Courses'
2. Scroll to 'Up & Going with JavaScript'
3. Clink 'Link'
4. Get 404

### Expected Behavior

Expected to be redirect to 3rd free JavaScript Course by Up & Going 

### Browsers Affected

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari 11
- [ ] Safari 10
- [ ] IE 11

### Device Affected

- [ ] Mobile
- [ ] Tablet
- [X] Computer

**Comment by samanthaming** [comment]
@baker-d oh yikes! Great catch! Let me fix this right now!! Thank you!!! (will be updated in my next deploy)
