### ISSUE TITLE
[Bug Report] Share links attribute title="something here"

### ISSUE THREAD

**Issue by peterpeterparker** [samanthaming/samanthaming.com#7]
### Describe the bug

Hi Samantha,

Of course I had to had a look to your "hacker news" link since your article gave me the idea to add it to my web component ;)

Doing so I noticed that all your social links have an attribute `title` which contains `something here`. I'm guessing that it isn't the expected behavior.

### Steps to Reproduce

See screenshot.

### Expected Behavior

I'm guessing a text like `Share this article on ....` instead of the placeholder `something here`.

### Screenshots

<img width="1343" alt="Capture d’écran 2020-02-07 à 18 05 23" src="https://user-images.githubusercontent.com/16886711/74049698-fcb77f80-49d4-11ea-97e9-5a1f6f815f31.png">

**Comment by samanthaming** [comment]
Hi Peter, thanks so much for catching this!!!! I knew it was too good to be true that I assumed there was no bug. Also great suggestion on what I should be in the title instead. I will work on a fix 💪

**Comment by peterpeterparker** [comment]
Coolio, happy to hear it helped!
